services:
  ollama:
    build:
      context: src/ollama
      dockerfile: Dockerfile
    ports:
      - 11434:11434
    volumes:
      - ollama-storage:/root/.ollama
      # For adding custom models on build
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    entrypoint:
      - "/usr/bin/bash"
      - "/entrypoint.sh"
    environment:
      - OLLAMA_KEEP_ALIVE="30m"
    gpus: all
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 5s
      retries: 2

  app:
    build:
      context: src/app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 2

volumes:
  ollama-storage: